sudo: false
cache: bundler
language: ruby
rvm:
  - 2.0.0
  - 2.1
  - 2.2
  - 2.3.0
  - ruby-head
  - rbx
  - jruby-9.0
env:
  - JRUBY_OPTS="--debug"
matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: rbx
before_install: gem update --remote bundler
install:
  - bundle install --retry=3
  - bundle exec yard config load_plugins true
script:
  - bundle exec rspec
  - bundle exec yard doctest
  - bundle exec rubocop
