sudo: false
cache: bundler
language: ruby
rvm:
  - 2.1
  - 2.2.4
  - 2.3.0
  - ruby-head
  - rbx
  - jruby-head
env:
  - JRUBY_OPTS="--debug"
matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: rbx
    - rvm: jruby-head
before_install: gem update --remote bundler
install:
  - bundle install --retry=3
  - bundle exec yard config load_plugins true
script:
  - bundle exec rspec
  - bundle exec yard doctest
  - bundle exec rubocop
addons:
  code_climate:
    repo_token: 2615201951ddd8934dccee806e223a2124ce5e73ec7b4505b92749bbb7636b7a
